#!/bin/sh

# remote for http://mixes.djfez.com

# needs external tools:
#  - lynx
#  - wget
#  - cat
#  - cut
#  - grep
#  - mkdir
#  - sed

dumpurls()
# get URL list
{
    lynx -dump "$@" | cut -c 7- | grep ^http:
}

abend()
# end with error
{
    echo "$@" 1>&2
    exit 1
}

parsePage()
# recursively get song style listings
{
    local STYLE PAGE NEXTPAGE STATE
    STYLE="$1"
    PAGE=$2
    NEXTPAGE=$(( $PAGE + 1 ))
    STATE=0
    
    dumpurls "$MIXESURL$STYLE/$PAGE/" | while read URL; do

	case $STATE in
	    0)
		if [ "$URL" = "http://donate.djfez.com/" ] ; then
		    STATE=1
		fi
		;;
	    
	    1)
		if [[ "$URL" =~ ^$MIXESURL[0-9][0-9][0-9][0-9]/$ ]] ; then
		    echo $URL
		    STATE=2
		fi
		;;

	    2)
		if [[ "$URL" =~ ^$MIXESURL[0-9][0-9][0-9][0-9]/$ ]] ; then
		    echo $URL
		else
		    if [ "$URL" = "$MIXESURL$STYLE/$NEXTPAGE/" ] ; then
			parsePage "$STYLE" $NEXTPAGE
		    else
			if [ "$URL" = "$MIXESURL" ] ; then
			    return
			fi
		    fi
		fi
		
	esac
	    
    done
}

BASEURL=http://mixes.djfez.com/
MIXESURL=${BASEURL}mixes/
DOWNLOADURL=${BASEURL}download/

ACTION="$1"
shift

case "$ACTION" in

    style)
        # list all styles
	dumpurls $MIXESURL | egrep '^http://mixes.djfez.com/mixes/[^0-9].*/$' | sed -e "s,$MIXESURL,," -e "s,/$,,"
	
	;;
    
    update)
	# update song list of style <style>
	STYLE="$1"
	shift

	if [ -z "$(echo $STYLE)" ] ; then
	    abend no style given
	fi

	DIR=styles/"$STYLE"
	mkdir -p "$DIR"
	parsePage "$STYLE" 1 | while read URL; do
	    NUMBER=${URL%/}
	    NUMBER=${NUMBER##*/}
	    
	    EXISTFILE="$DIR/$NUMBER"
	    INFOFILE="${EXISTFILE}.info"

	    touch "$EXISTFILE"

	    if [ ! -e "$INFOFILE" ] ; then
		lynx --dump --hiddenlinks=ignore --nolist "$URL" \
		    | sed -n -e '/^Mixes/{:l1 p; n; b l1}' \
		    | sed -n -e '/Link Link to this mix/q;p' \
		    | (read; read; read; read; cut -c 4-) \
		    > "$INFOFILE"
	    fi

	    echo -n .
	done
	echo
	
	;;

    upgrade)
	# download missing songs of style <style>
	STYLE="$1"
	shift

	if [ -z "$(echo $STYLE)" ] ; then
	    abend no style given
	fi

	set +e
	cd "styles/$STYLE"
	
	for NUMBER in ????; do
	    if [ -e "$NUMBER.mp3" ] ; then
		echo skipping "#$NUMBER"
	    else
		echo -n downloading "#$NUMBER"...
		TARGETFILE="$NUMBER.mp3"
		TMPFILE="$TARGETFILE.tmp"
		wget -qO"$TMPFILE" "${DOWNLOADURL}${NUMBER}/"
		mv "$TMPFILE" "$TARGETFILE"
		echo ok
		sleep 60 # don't hammer their servers
	    fi
	done
	;;
    
    *)
	# show help text
	cat <<EOF
usage:
djfez style                      - list all styles
djfez update <style>             - update song list of style <style>
djfez upgrade <style>            - download missing songs of style <style>
EOF
	# todo: cleanup to kill .tmp files
	;;

esac
